### 
GET http://localhost:3003/api/v1/usuarios/68409678c8ce0f7dbfc02b95


###
POST  http://localhost:3003/api/v1/usuarios/
Content-Type: application/json

{
        "name": "Jhon",
        "username": "Perez",
        "email": "perezjhon2010@gmail.com"
         }

###
PATCH  http://localhost:3003/api/v1/usuarios/6841ef371639a48814ff0201
Content-Type: application/json

{
        
        "email": "pfgdgjhone0@gmail.com"
         }